name: ioc
description: The most simple Ioc Container of Dart and Flutter
version: 0.2.1
homepage: https://github.com/copydog/ioc.dart
author: copydog <775150@qq.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
